# Generated by Django 4.2.2 on 2023-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0002_alter_user_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Follow',
        ),
    ]
